# Jobs for sfdx-core
jobs:
  # Use the default promote script
  - name: publish
    skipTests: true
  - name: promote


  # Use the default promote script
  #- name: publish
  #  testTarget: test-with-coverage
  #  envMap:
  #    - 'EMAIL': 'alm-cli@salesforce.com'
  #- name: promote