version: 2
jobs:
  base: &base
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
  node-latest: &test
    <<: *base
    steps:
      - checkout
      - restore_cache: &restore_cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run:
          name: Bootstraping
          command: yarn bootstrap
      - run:
          name: Building
          command: yarn build
      - run:
          name: Testing
          command: yarn ci-test
      - run:
          name: Submitting code coverage to codecov
          command: |
            ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *base
    steps:
      - add_ssh_keys:
          fingerprints:
            - '62:cb:86:a5:2b:57:ef:a8:a1:c2:cf:38:50:d0:61:58'
      - checkout
      - restore_cache: &restore_cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set Github Info
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GH_EMAIL"
            git config user.name "Deployment Bot"
      - run:
          name: Install Lerna
          command: npm install -g lerna
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run:
          name: Bootstraping
          command: yarn bootstrap
      - run:
          name: Compiling
          command: yarn compile
      - run:
          name: Set Credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing
          command: lerna publish --conventional-commits -y
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  merge:
    <<: *base
    steps:
      - add_ssh_keys:
          fingerprints:
            - '62:cb:86:a5:2b:57:ef:a8:a1:c2:cf:38:50:d0:61:58'
      - checkout
      - run:
          name: Set Github Info
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GH_EMAIL"
            git config user.name "Deployment Bot"
      - run: git fetch
      - run: git checkout develop
      - run: git pull origin develop
      - run: git merge origin/master
      - run: git push origin develop

workflows:
  version: 2
  'sfdx-dev-packages':
    jobs:
      - node-latest
      - node-8
      - release:
          filters:
            branches: { only: master }
          requires:
            - node-latest
            - node-8
      - merge:
          filters:
            branches: { only: master }
          requires:
            - release
