version: 2
jobs:
  base: &base
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
  node-latest: &test
    <<: *base
    steps:
      - checkout
      - restore_cache: &restore_cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run:
          name: Bootstraping
          command: yarn bootstrap
      - run:
          name: Testing
          command: yarn build
      - run:
          name: Submitting code coverage to codecov
          command: |
            ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *base
    steps:
      - checkout
      - restore_cache: &restore_cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run:
          name: Bootstraping
          command: yarn bootstrap
      # - run: lerna publish -y
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  'sfdx-core':
    jobs:
      - node-latest
      - node-8
      - release:
          filters:
            branches: { only: master }
          requires:
            - node-latest
            - node-8
